services:
  backend:
    build: ./nawy-real-estate-back
    container_name: backend_service
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      MOOD: PROD
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - ./nawy-real-estate-back/.env

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_estate
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


  frontend:
    build: ./nawy-real-estate-front
    container_name: frontend_service
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pg_data: